export const COLORS = [
    { colorName: 'AliceBlue', hexCode: '#F0F8FF' },
    { colorName: 'Aqua', hexCode: '#00FFFF' },
    { colorName: 'Aquamarine', hexCode: '#7FFFD4' },
    { colorName: 'Azure', hexCode: '#F0FFFF' },
    { colorName: 'Beige', hexCode: '#F5F5DC' },
    { colorName: 'Black', hexCode: '#000000' },
    { colorName: 'BlanchedAlmond', hexCode: '#FFEBCD' },
    { colorName: 'Blue', hexCode: '#0000FF' },
    { colorName: 'BlueViolet', hexCode: '#8A2BE2' },
    { colorName: 'Brown', hexCode: '#A52A2A' },
    { colorName: 'BurlyWood', hexCode: '#DEB887' },
    { colorName: 'CadetBlue', hexCode: '#5F9EA0' },
    { colorName: 'Chartreuse', hexCode: '#7FFF00' },
    { colorName: 'Chocolate', hexCode: '#D2691E' },
    { colorName: 'Coral', hexCode: '#FF7F50' },
    { colorName: 'CornflowerBlue', hexCode: '#6495ED' },
    { colorName: 'Cornsilk', hexCode: '#FFF8DC' },
    { colorName: 'Crimson', hexCode: '#DC143C' },
    { colorName: 'Cyan', hexCode: '#00FFFF' },
    { colorName: 'DarkBlue', hexCode: '#00008B' },
    { colorName: 'DarkCyan', hexCode: '#008B8B' },
    { colorName: 'DarkGoldenRod', hexCode: '#B8860B' },
  ];